### ISSUE TITLE
Shut Down and Log Out dialogs cannot be Escaped

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-session#82]
As @Blast-City mentioned, you can't use Escape key to close them. Esc should just cancel them.

**Comment by 4jNsY6fCVqZv** [comment]
@danrabbit Although it's written by @cassidyjames in your great new blog - thanks for that! - that this should work now, I have observed something. By default, the Shut Down and Log Out dialogs have no focus. And without the focus the solution with the Esc key doesn't work quite smoothly because I always need an additional click to create the focus first. I understood that you wanted to simplify it. Am I wrong?

**Comment by 4jNsY6fCVqZv** [comment]
Or is the version https://github.com/elementary/wingpanel-indicator-session/releases/tag/2.2.5 not rolled out via AppCenter yet?

**Comment by ryonakano** [comment]
@4jNsY6fCVqZv The issue that Shut Down and Log Out dialogs are not focused is [a different issue](https://github.com/elementary/wingpanel/issues/228) and fixed in (this Pull Request in Wingpanel)[https://github.com/elementary/wingpanel/pull/229], but a new release of Wingpanel is not published so that the issue still happens.

**Comment by 4jNsY6fCVqZv** [comment]
@ryonakano Oh, thank you. I'm glad to read that. I thought it was a special issue from wingpanel-indicator-session. I wasn't aware that it was part of the general focus problem of Wingpanel. Then I wait gratefully until the fix is released.
